import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CommonLayout from "@/components/features/layout/CommonLayout";

export const metadata: Metadata = {
  title: "S-mining",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body className={`text-sm text-white  antialiased`}>
        <CommonLayout>{children}</CommonLayout>
      </body>
    </html>
  );
}
